dist: xenial
language: python
cache: pip

branches:
    only:
        - develop
        - master

python:
    - "3.7"

services:
    - postgresql

before_script:
    - psql -c 'create database yumljira;' -U postgres

install:
    - pip install -r requirements/local.txt
    - cp yumljira/settings/db.base.py yumljira/settings/db.py
    - npm install

script:
    - pytest
    - npm run test

notifications:
    email: false

