# Generated by Django 2.2.5 on 2019-09-20 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connected_tasks', to='projects.Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('BUG', 'Bug'), ('SUBTASK', 'Sub task'), ('STORY', 'Story')], default='SUBTASK', max_length=50, verbose_name='Task type'),
        ),
    ]
