# Generated by Django 2.2.5 on 2019-09-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='key',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Project key'),
        ),
    ]
