# Generated by Django 2.2.5 on 2019-09-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='key',
            field=models.CharField(max_length=30, verbose_name='Project key'),
        ),
    ]
