# Generated by Django 2.2.5 on 2019-10-02 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190928_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='board_type',
            field=models.CharField(choices=[('kanban', 'kanban'), ('scrum', 'scrum')], default='kanban', max_length=50),
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number_in_board', models.PositiveSmallIntegerField()),
                ('should_show', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.Project')),
            ],
            options={
                'unique_together': {('project', 'number_in_board')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='projects.Column'),
        ),
    ]
