# Generated by Django 2.2.5 on 2019-10-02 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_sprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='projects.Project'),
        ),
    ]
