# Generated by Django 2.2.5 on 2019-10-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20191002_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='column',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
