# Generated by Django 2.2.5 on 2019-10-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_remove_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='removable',
            field=models.BooleanField(default=True),
        ),
    ]
