# Generated by Django 2.2.5 on 2019-10-04 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_column_removable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='column',
            unique_together=set(),
        ),
    ]
